from setuptools import setup, find_packages

setup(
    name="llm-manager",
    version="0.1.0",
    package_dir={"": "src"},
    packages=find_packages(where="src"),
    include_package_data=True,
    package_data={
        "llm_manager": ["config.yaml"],
    },
    install_requires=[
        "openai>=1.0.0",
        "anthropic>=0.5.0",
        "pyyaml>=6.0",
        "python-dotenv>=1.0.0",
        "tenacity>=8.2.0",
        "tiktoken>=0.4.0",
        "requests>=2.28.0",
        "typing-extensions>=4.5.0",
    ],
    extras_require={
        "dev": [
            "pytest>=7.0.0",
            "black>=23.0.0",
            "isort>=5.12.0",
            "mypy>=1.0.0",
            "flake8>=6.0.0",
            "pytest-cov>=4.0.0",
        ],
    },
    python_requires=">=3.8",
    description="A unified manager for interacting with various LLM APIs",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    author="Your Name",
    author_email="your.email@example.com",
    url="https://github.com/yourusername/llm-manager",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Topic :: Software Development :: Libraries :: Python Modules",
    ],
    keywords="llm, ai, openai, anthropic, claude, gpt",
    license="MIT",
)
