providers:
  azure: 
    enabled: true
    models:
      gpt4o: 
        api_key: "${AZURE_API_KEY}"
        api_version: "${AZURE_API_VERSION:-2023-05-15}"
        azure_endpoint: "${AZURE_API_BASE}"
        azure_deployment: "${AZURE_DEPLOYMENT}"
        model_id: "gpt-4o"
      
      o1_mini:
        api_key: "${AZURE_API_KEY}"
        api_version: "${AZURE_API_VERSION:-2023-05-15}"
        azure_endpoint: "${AZURE_API_BASE}"
        azure_deployment: "${AZURE_o1_mini_DEPLOYMENT}"
        model_id: "o1-mini"

      o1:
        api_key: "${AZURE_o1_API_KEY}"
        api_version: "${AZURE_o1_API_VERSION:-2024-12-01-preview}"
        azure_endpoint: "${AZURE_o1_API_BASE}"
        azure_deployment: "${AZURE_o1_DEPLOYMENT}"
        model_id: "o1"
        reasoning_effort:
          type: enabled
          default: medium
          allowed_values: [low, medium, high]
      
      o3_mini:
        api_key: "${AZURE_o1_API_KEY}"
        api_version: "${AZURE_o1_API_VERSION:-2024-12-01-preview}"
        azure_endpoint: "${AZURE_o1_API_BASE}"
        azure_deployment: "${AZURE_o3_mini_DEPLOYMENT}"
        model_id: "o3-mini"
        reasoning_effort:
          type: enabled
          default: medium
          allowed_values: [low, medium, high]
      
      o3:
        api_key: "${AZURE_o1_API_KEY}"
        api_version: "${AZURE_o1_API_VERSION:-2024-12-01-preview}"
        azure_endpoint: "${AZURE_o3_API_BASE}"
        azure_deployment: "${AZURE_o3_DEPLOYMENT}"
        model_id: "o3"
        reasoning_effort:
          type: enabled
          default: medium
          allowed_values: [low, medium, high]

      o4_mini:
        api_key: "${AZURE_o1_API_KEY}"
        api_version: "${AZURE_o1_API_VERSION:-2024-12-01-preview}"
        azure_endpoint: "${AZURE_o1_API_BASE}"
        azure_deployment: "${AZURE_o4_mini_DEPLOYMENT}"
        model_id: "o4-mini"
        reasoning_effort:
          type: enabled
          default: medium
          allowed_values: [low, medium, high]

  anthropic:
    enabled: true
    api_key: "${ANTHROPIC_API_KEY}"
    models:
      claude_3_5:
        model_id: "claude-3-5-sonnet-20241022"
        max_tokens: 1000
        temperature: 0.7
        system: ""
      
      claude_3_7:
        model_id: "claude-3-7-sonnet-20250219"
        max_tokens: 20000
        temperature: 0.7
        system: ""
        thinking:
          type: "enabled"
      
      # claude_3_7_thinking_8k:
      #   model_id: "claude-3-7-sonnet-20250219"
      #   max_tokens: 20000
      #   temperature: 1.0
      #   system: ""
      #   thinking:
      #     type: "enabled"
      #     budget_tokens: 8000

      # claude_3_7_thinking_16k:
      #   model_id: "claude-3-7-sonnet-20250219"
      #   max_tokens: 20000
      #   temperature: 1.0
      #   system: ""
      #   thinking:
      #     type: "enabled"
      #     budget_tokens: 8000
      
      # claude_3_7_thinking_64k:
      #   model_id: "claude-3-7-sonnet-20250219"
      #   max_tokens: 128000
      #   temperature: 1.0
      #   system: "You are a helpful AI assistant."
      #   thinking:
      #     type: "enabled"
      #     budget_tokens: 64000
  
  abacus:
    enabled: true
    api_key: "${ABACUS_API_KEY}"
    models:
      gemini_2_5_pro:
        model_id: "GEMINI_2_5_PRO"
        temperature: 0.7
        system: ""
      
      deepseek_r1:
        model_id: "DEEPSEEK_R1"
        temperature: 0.7
        system: ""

# Default settings
default_provider: "${DEFAULT_PROVIDER:-azure}"
default_model: "${DEFAULT_MODEL:-gpt4o}"
