providers:
  azure: 
    enabled: true
    models:
      gpt4o: 
        api_key: "${AZURE_API_KEY}"
        api_version: "${AZURE_API_VERSION:-2023-05-15}"
        azure_endpoint: "${AZURE_API_BASE}"
        azure_deployment: "${AZURE_DEPLOYMENT}"
        model_id: "gpt-4o"
      
      o1-mini:
        api_key: "${AZURE_API_KEY}"
        api_version: "${AZURE_API_VERSION:-2023-05-15}"
        azure_endpoint: "${AZURE_API_BASE}"
        azure_deployment: "${AZURE_o1_mini_DEPLOYMENT}"
        model_id: "o1-mini"

      o1:
        api_key: "${AZURE_o1_API_KEY}"
        api_version: "${AZURE_o1_API_VERSION:-2024-12-01-preview}"
        azure_endpoint: "${AZURE_o1_API_BASE}"
        azure_deployment: "${AZURE_o1_DEPLOYMENT}"
        model_id: "o1"
      
      o3-mini:
        api_key: "${AZURE_o1_API_KEY}"
        api_version: "${AZURE_o1_API_VERSION:-2024-12-01-preview}"
        azure_endpoint: "${AZURE_o1_API_BASE}"
        azure_deployment: "${AZURE_o3_mini_DEPLOYMENT}"
        model_id: "o3-mini"
      
      o3:
        api_key: "${AZURE_o1_API_KEY}"
        api_version: "${AZURE_o1_API_VERSION:-2025-04-01-preview}"
        azure_endpoint: "${AZURE_o3_API_BASE}"
        azure_deployment: "${AZURE_o3_DEPLOYMENT}"
        model_id: "o3"

      o4-mini:
        api_key: "${AZURE_o1_API_KEY}"
        api_version: "${AZURE_o1_API_VERSION:-2024-12-01-preview}"
        azure_endpoint: "${AZURE_o1_API_BASE}"
        azure_deployment: "${AZURE_o4_mini_DEPLOYMENT}"
        model_id: "o4-mini"

      o4-mini:
        api_key: "${AZURE_o1_API_KEY}"
        api_version: "${AZURE_o1_API_VERSION:-2024-12-01-preview}"
        azure_endpoint: "${AZURE_o1_API_BASE}"
        azure_deployment: "${AZURE_o4_mini_DEPLOYMENT}"
        model_id: "o4-mini"

      gpt-5:
        api_key: "${AZURE_o1_API_KEY}"
        api_version: "${AZURE_o1_API_VERSION:-2025-03-01-preview}"
        azure_endpoint: "${AZURE_o1_API_BASE}"
        azure_deployment: "${AZURE_gpt5_DEPLOYMENT}"
        model_id: "gpt-5"

  anthropic:
    enabled: true
    api_key: "${ANTHROPIC_API_KEY}"
    models:
      claude-sonnet-4:
        model_id: "claude-sonnet-4-20250514"
      
      claude-sonnet-3.5:
        model_id: "claude-3-5-sonnet-20241022"
      
      claude-sonnet-3.7:
        model_id: "claude-3-7-sonnet-20250219"
  
  abacus:
    enabled: true
    api_key: "${ABACUS_API_KEY}"
    models:
      gemini-2.5-pro:
        model_id: "GEMINI_2_5_PRO"

      deepseek-r1:
        model_id: "DEEPSEEK_R1"

      o3-low:
        model_id: "O3_LOW"

      o3-medium:
        model_id: "O3_MEDIUM"

      o3-high:
        model_id: "O3_HIGH"

      o4-mini:
        model_id: "OPENAI_O4_MINI"

      o4-mini-high:
        model_id: "OPENAI_O4_MINI_HIGH"
      
  bedrock:
      enabled: true
      region_name: "us-east-2"
      aws_access_key_id: "${AWS_ACCESS_KEY}"
      aws_secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
      models:
        claude-sonnet-3.7:
          model_id: "arn:aws:bedrock:us-east-2:931886963315:inference-profile/us.anthropic.claude-3-7-sonnet-20250219-v1:0"

        claude-sonnet-4:
          model_id: "arn:aws:bedrock:us-east-2:931886963315:inference-profile/us.anthropic.claude-sonnet-4-20250514-v1:0"

        claude-opus-4:
          model_id: "arn:aws:bedrock:us-east-2:931886963315:inference-profile/anthropic.claude-opus-4-20250514-v1:0"

  vLLM:
    enabled: true
    models:
      qwen2-7b:
        model_id: "Qwen/Qwen2-7B-Instruct"


# Default settings
default_provider: "${DEFAULT_PROVIDER:-azure}"
default_model: "${DEFAULT_MODEL:-gpt4o}"
